apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/microsoft/kalypso-control-plane
  branch: main
  path: .
  commit: 3021a77921cdc221a7c11c8fecbc7e57996e6b66
